// Parchment brand mark — a parchment scroll on the brand-blue tile.
// One source of truth for the in-app logo; the favicon (src/app/icon.svg) and
// the PWA icons (public/icons/*, generated by scripts/gen-icons.mjs) use the
// SAME artwork. Decorative by default (aria-hidden) since it sits beside the
// "Parchment" wordmark; pass a `title` to make it a standalone labelled image.
export function ParchmentLogo({
  size = 20,
  title,
  className,
}: {
  size?: number
  title?: string
  className?: string
}) {
  return (
    <svg
      viewBox="0 0 100 100"
      width={size}
      height={size}
      className={className}
      role={title ? 'img' : undefined}
      aria-hidden={title ? undefined : true}
      aria-label={title}
      focusable="false"
    >
      {title ? <title>{title}</title> : null}
      <rect x="2" y="2" width="96" height="96" rx="22" fill="#1A73E8" />
      <path d="M32 30 q0 -8 8 -8 h28 q-6 4 -6 12 v44 q0 8 -8 8 h-28 q6 -4 6 -12 Z" fill="#ffffff" />
      <path
        d="M62 22 q8 0 8 8 v40 q0 8 -8 8"
        fill="none"
        stroke="#aecbfa"
        strokeWidth="4.5"
        strokeLinecap="round"
      />
      <rect x="38" y="40" width="20" height="4" rx="2" fill="#1A73E8" />
      <rect x="38" y="50" width="20" height="4" rx="2" fill="#1A73E8" />
      <rect x="38" y="60" width="13" height="4" rx="2" fill="#8ab4f8" />
    </svg>
  )
}
