// @vitest-environment node
// J7-3: docx fidelity GATE. Imports a tiny committed fixture .docx (headings,
// bold/italic, a bullet list, a table) through the real mammoth → markdown →
// markdownToJson pipeline and asserts the resulting ProseMirror JSON contains the
// expected node types / marks (a documented fidelity floor). No network / db.
//
// The fixture is generated by scripts/gen-docx-fixture.mjs (committed alongside it)
// and lives at tests/fixtures/sample.docx.

import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { importToPmJson } from '@/lib/import'

const FIXTURE = fileURLToPath(new URL('../fixtures/sample.docx', import.meta.url))

// Recursively collect every node `type` and mark `type` in a PM JSON tree.
function collect(node: unknown, types: Set<string>, marks: Set<string>): void {
  if (!node || typeof node !== 'object') return
  const n = node as { type?: unknown; marks?: unknown; content?: unknown }
  if (typeof n.type === 'string') types.add(n.type)
  if (Array.isArray(n.marks)) {
    for (const m of n.marks) {
      if (m && typeof m === 'object' && typeof (m as { type?: unknown }).type === 'string') {
        marks.add((m as { type: string }).type)
      }
    }
  }
  if (Array.isArray(n.content)) {
    for (const c of n.content) collect(c, types, marks)
  }
}

describe('docx fidelity (J7-3 gate)', () => {
  it('imports the fixture without throwing and produces a doc', async () => {
    const bytes = new Uint8Array(await readFile(FIXTURE))
    const result = await importToPmJson('docx', bytes, 'sample.docx')
    expect(result.json.type).toBe('doc')
  })

  it('preserves headings, bold, italic, and lists (fidelity floor)', async () => {
    const bytes = new Uint8Array(await readFile(FIXTURE))
    const result = await importToPmJson('docx', bytes, 'sample.docx')

    const types = new Set<string>()
    const marks = new Set<string>()
    collect(result.json, types, marks)

    // Fidelity floor — these node/mark kinds MUST survive the docx round-trip.
    // (If mammoth/turndown drops one of these, that's a real fidelity regression,
    // not a silently-accepted loss.)
    expect(types).toContain('heading')
    expect(types).toContain('bulletList')
    expect(types).toContain('listItem')
    expect(marks).toContain('bold')
    expect(marks).toContain('italic')
  })

  // DOCUMENTED FIDELITY EXCEPTION (J7-3): GFM/HTML tables do NOT round-trip into a
  // ProseMirror `table` NODE on import. The mammoth → turndown step emits an HTML
  // <table>, and markdownToJson only reconstructs a `table` node from Parchment's
  // own `parchment:table` JSON fence (parse.ts:393) — not from raw markdown/HTML
  // tables. So an imported docx table degrades to inline text/paragraphs rather
  // than a structured table. This is an explicit, asserted loss (the CELL TEXT
  // still survives), not a silent one. Lifting it would require a GFM-table →
  // parchment-table bridge in the import pipeline (future work).
  it('does NOT reconstruct a table node, but preserves the cell text (documented loss)', async () => {
    const bytes = new Uint8Array(await readFile(FIXTURE))
    const result = await importToPmJson('docx', bytes, 'sample.docx')

    const types = new Set<string>()
    const marks = new Set<string>()
    collect(result.json, types, marks)

    // The structured table node is the documented loss.
    expect(types.has('table')).toBe(false)

    // …but the cell content is not dropped — it survives as text somewhere.
    const flat = JSON.stringify(result.json)
    expect(flat).toContain('A1')
    expect(flat).toContain('B1')
  })

  it('derives the title from the docx H1', async () => {
    const bytes = new Uint8Array(await readFile(FIXTURE))
    const result = await importToPmJson('docx', bytes, 'sample.docx')
    expect(result.title).toBe('Sample Document')
  })
})
